travis:
  secure:
    BINSTAR_TOKEN: jOB9ZjASEDEfhIb7MznP54Ke8lkDdQtjKGvR7288gfYdhtDDimLU4ojrJ4IUrgLAgpoFprgZ99RgOsm5WkaBEwUZJG18CIULAzR8uscs13qf8cxjmAcAA42phrwxosVWJcHiIBS4TVoTFlDrQJkv6UUeSSWiAy2pL5e1Aum8dfLC4FRHQMqP0AJD7RtW08vcGAE6S17j/m9zjPGtIcb9bpEfKKQ0YluUmHC++jIbUkZMD/oRFhvQOLZyx7gZhI0UdTU/DkMvDEY2NrfqwZMpNJ9CAds6jN+YO+QVp965tRTMVzaX0gvUcebbm/OPyAgtlbkKuHrRn1LOWOtvjZfflYxXF0FBUclPD/LmNuy+iT1MIE8FwSBT7bv5pOuxXAo9VjQ+MLA+lFAMBhHqYBs3AR6BMs8L2HPE4Z7Xc/kgazMcyIyyZ3lHmgATEQJeggN0fvocYAaWmRGEE7SJ1+haXPz4egg7+x8wvqvlJMIJfwFDFgwjv370VuQ5gTPAFDShz3GBrA4aoBoHmD693An08jEFYsvlF2/3imkuBKXaPnntSLRcufGHYY9q8gONfurqfKBHKz1I75rx+fyj277awDHzAL6XG68kb6ytK9qTegfvIwwzPQUGuhlkhWgG1v36tufByUVIZ+ZbtDe+O4P+cFKEvITueRrfZtJzE9PrgBA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
